"""add chane about_author field type

Revision ID: 3ac6eda9a527
Revises: 9fa8ef8ab51d
Create Date: 2023-08-19 14:08:53.217213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac6eda9a527'
down_revision = '9fa8ef8ab51d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('about_author',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('about_author',
               existing_type=sa.Text(length=500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
