"""add chane about_author field type

Revision ID: 9fa8ef8ab51d
Revises: 3a06d21da99c
Create Date: 2023-08-19 13:51:58.033554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa8ef8ab51d'
down_revision = '3a06d21da99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('about_author',
               existing_type=sa.TEXT(length=500),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('about_author',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
